export interface Product {
  id: string;
  slug: string;
  name: string;
  tagline: string;
  description: string;
  price: number; // in cents
  priceDisplay: string;
  image: string;
  stripePrice?: string;
  contents: string[];
  badge?: string;
  /** Category also doubles as the TCG game name for TCG products */
  category: string;
  inStock: boolean;
  createdAt: string; // ISO date string for "newest" sort
}

export const products: Product[] = [
  // ─── Mystery Crates ────────────────────────────────────────────────────────
  {
    id: "mystery-crate-bronze",
    slug: "mystery-crate-bronze",
    name: "Bronze Mystery Crate",
    tagline: "Your first step into the unknown.",
    description:
      "The Bronze Mystery Crate is the perfect entry point — one curated mystery TCG booster pack selected from our rotating stock, wrapped and ready to surprise. No duplicates guaranteed within a single order.",
    price: 1499,
    priceDisplay: "£14.99",
    image: "/images/mini.svg",
    contents: [
      "1 mystery TCG booster pack",
      "Branded tissue wrap",
      "Collector info card",
    ],
    badge: "Starter",
    category: "Mystery Crates",
    inStock: true,
    createdAt: "2026-04-04",
  },
  {
    id: "mystery-crate-silver",
    slug: "mystery-crate-silver",
    name: "Silver Mystery Crate",
    tagline: "More packs. More possibilities.",
    description:
      "The Silver Mystery Crate steps things up with three mystery booster packs spanning at least two different TCG titles. Expect variety, surprise, and at least one pack from a current competitive set.",
    price: 3499,
    priceDisplay: "£34.99",
    image: "/images/studio.svg",
    contents: [
      "3 mystery TCG booster packs (2+ different games)",
      "1 pack guaranteed from a current competitive set",
      "Branded tissue wrap",
      "2× collector info cards",
      "Sticker",
    ],
    badge: "Popular",
    category: "Mystery Crates",
    inStock: true,
    createdAt: "2026-04-04",
  },
  {
    id: "mystery-crate-gold",
    slug: "mystery-crate-gold",
    name: "Gold Mystery Crate",
    tagline: "Six packs of pure anticipation.",
    description:
      "The Gold Mystery Crate is our most immersive mystery tier — six booster packs across three or more TCG titles, delivered in a premium matte-black box. At least one pack is sourced from a high-value Japanese set.",
    price: 6999,
    priceDisplay: "£69.99",
    image: "/images/midnight.svg",
    contents: [
      "6 mystery TCG booster packs (3+ different games)",
      "1 pack guaranteed from a Japanese TCG set",
      "Matte black gift box with gold foil branding",
      "Premium tissue wrap",
      "4× collector info cards",
      "Exclusive Noir Crates sticker set",
    ],
    badge: "Premium",
    category: "Mystery Crates",
    inStock: true,
    createdAt: "2026-04-04",
  },
  {
    id: "mystery-crate-platinum",
    slug: "mystery-crate-platinum",
    name: "Platinum Mystery Crate",
    tagline: "The ultimate mystery experience.",
    description:
      "Our most premium crate tier — ten booster packs spanning four or more titles, with a guaranteed Japanese booster box included. The Platinum Mystery Crate is for the serious collector who loves surprises.",
    price: 9999,
    priceDisplay: "£99.99",
    image: "/images/midnight.svg",
    contents: [
      "10 mystery TCG booster packs (4+ different games)",
      "1 full Japanese TCG booster box guaranteed",
      "Luxury matte-black box with platinum foil",
      "Premium tissue wrap",
      "6× collector info cards",
      "Exclusive Noir Crates enamel pin",
      "Sticker set",
    ],
    badge: "Limited",
    category: "Mystery Crates",
    inStock: true,
    createdAt: "2026-04-04",
  },

  // ─── Blind Boxes ───────────────────────────────────────────────────────────
  {
    id: "tcg-blind-box-single",
    slug: "tcg-blind-box-single",
    name: "TCG Blind Box — Single Pack",
    tagline: "One pack. Complete surprise.",
    description:
      "A single sealed booster pack from a mystery TCG title — you won't know which game until you open the box. Could be Pokémon, Yu-Gi-Oh!, One Piece, or another top TCG. The purest unboxing thrill.",
    price: 799,
    priceDisplay: "£7.99",
    image: "/images/mini.svg",
    contents: [
      "1 mystery TCG booster pack (game revealed on opening)",
      "Collector info card",
    ],
    badge: "New",
    category: "Blind Boxes",
    inStock: true,
    createdAt: "2026-04-04",
  },
  {
    id: "tcg-blind-box-trio",
    slug: "tcg-blind-box-trio",
    name: "TCG Blind Box — Trio",
    tagline: "Three blinds. Triple the surprise.",
    description:
      "Three individually wrapped mystery TCG booster packs, each sealed in a black envelope so you can't tell which game you're opening until the moment arrives. All three will be different titles.",
    price: 1999,
    priceDisplay: "£19.99",
    image: "/images/studio.svg",
    contents: [
      "3 mystery TCG booster packs — all different games",
      "Each pack individually wrapped in a sealed black envelope",
      "3× collector info cards",
    ],
    badge: "Popular",
    category: "Blind Boxes",
    inStock: true,
    createdAt: "2026-04-04",
  },
  {
    id: "pokemon-blind-box-japanese-single",
    slug: "pokemon-blind-box-japanese-single",
    name: "Pokémon Japanese Blind Box — Single Pack",
    tagline: "A Japanese Pokémon pack — surprise set.",
    description:
      "One Japanese Pokémon booster pack from a mystery Scarlet & Violet era set. The specific set isn't revealed until you open the box — your pull could come from any of our current Japanese stock.",
    price: 499,
    priceDisplay: "£4.99",
    image: "/images/mini.svg",
    contents: [
      "1 Japanese Pokémon booster pack (mystery Scarlet & Violet set)",
      "10 cards per pack",
      "Collector info card",
    ],
    category: "Blind Boxes",
    inStock: true,
    createdAt: "2026-04-04",
  },
  {
    id: "yugioh-blind-box-single",
    slug: "yugioh-blind-box-single",
    name: "Yu-Gi-Oh! Blind Box — Single Pack",
    tagline: "Duel in the dark — mystery set revealed on opening.",
    description:
      "One Yu-Gi-Oh! booster pack from a mystery set in our current stock. You won't know the set name until you tear open the black wrapping. Could be anything from a recent main set to a special release.",
    price: 449,
    priceDisplay: "£4.49",
    image: "/images/mini.svg",
    contents: [
      "1 Yu-Gi-Oh! booster pack (mystery set)",
      "9 cards per pack",
      "Collector info card",
    ],
    category: "Blind Boxes",
    inStock: true,
    createdAt: "2026-04-04",
  },

  // ─── Trading Card Games ────────────────────────────────────────────────────
  // ── Pokémon Japanese Booster Boxes ─────────────────────────────────────────
  {
    id: "japanese-ninja-spinner-booster-box",
    slug: "japanese-ninja-spinner-booster-box",
    name: "Japanese Ninja Spinner Booster Box",
    tagline: "Spin your way to rare Japanese pulls.",
    description:
      "A full Japanese booster box from the Ninja Spinner set. Contains 30 booster packs bursting with ninja-themed Pokémon and exclusive Japanese artwork not found in Western releases.",
    price: 9000,
    priceDisplay: "£90.00",
    image: "/images/studio.svg",
    contents: [
      "30× Ninja Spinner booster packs (10 cards each)",
      "Chance at rare holos, ultra rares, and secret rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-28",
  },
  {
    id: "japanese-mega-munikis-zero-booster-box",
    slug: "japanese-mega-munikis-zero-booster-box",
    name: "Japanese MEGA Munikis Zero Booster Box",
    tagline: "Zero limits on rare pulls.",
    description:
      "A full Japanese booster box from the MEGA Munikis Zero set. Contains 30 booster packs featuring powerful MEGA Pokémon and stunning Japanese-exclusive special art.",
    price: 8000,
    priceDisplay: "£80.00",
    image: "/images/mini.svg",
    contents: [
      "30× MEGA Munikis Zero booster packs (10 cards each)",
      "Chance at MEGA EX and full-art ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-27",
  },
  {
    id: "japanese-mega-dream-ex-booster-box",
    slug: "japanese-mega-dream-ex-booster-box",
    name: "Japanese MEGA Dream ex Booster Box",
    tagline: "Dream big with every Japanese pull.",
    description:
      "A full Japanese booster box from the MEGA Dream ex set, packed with powerful EX Pokémon cards and stunning Japanese-exclusive special art. Contains 30 booster packs ideal for collectors.",
    price: 11600,
    priceDisplay: "£116.00",
    image: "/images/midnight.svg",
    contents: [
      "30× MEGA Dream ex booster packs (10 cards each)",
      "Chance at EX and full-art ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-26",
  },
  {
    id: "japanese-mega-inferno-x-booster-box",
    slug: "japanese-mega-inferno-x-booster-box",
    name: "Japanese MEGA Inferno X Booster Box",
    tagline: "Feel the blazing heat of MEGA power.",
    description:
      "A full Japanese booster box from the MEGA Inferno X set, igniting your collection with fierce Fire-type Pokémon and exclusive Japanese artwork. Contains 30 booster packs of raw power.",
    price: 11500,
    priceDisplay: "£115.00",
    image: "/images/studio.svg",
    contents: [
      "30× MEGA Inferno X booster packs (10 cards each)",
      "Chance at MEGA EX and full-art ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-25",
  },
  {
    id: "japanese-mega-symphonia-booster-box",
    slug: "japanese-mega-symphonia-booster-box",
    name: "Japanese MEGA Symphonia Booster Box",
    tagline: "A symphony of rare pulls.",
    description:
      "A full Japanese booster box from the MEGA Symphonia set, celebrating harmonious Pokémon battles and stunning orchestral-themed Japanese artwork. Contains 30 booster packs.",
    price: 8500,
    priceDisplay: "£85.00",
    image: "/images/mini.svg",
    contents: [
      "30× MEGA Symphonia booster packs (10 cards each)",
      "Chance at MEGA EX and full-art ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-24",
  },
  {
    id: "japanese-mega-brave-booster-box",
    slug: "japanese-mega-brave-booster-box",
    name: "Japanese MEGA Brave Booster Box",
    tagline: "Be brave, pull rare.",
    description:
      "A full Japanese booster box from the MEGA Brave set, honouring the bravest Pokémon in bold Japanese artwork. Contains 30 booster packs packed with powerful MEGA cards.",
    price: 8500,
    priceDisplay: "£85.00",
    image: "/images/midnight.svg",
    contents: [
      "30× MEGA Brave booster packs (10 cards each)",
      "Chance at MEGA EX and full-art ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-23",
  },
  {
    id: "japanese-black-bolt-sv11b-booster-box",
    slug: "japanese-black-bolt-sv11b-booster-box",
    name: "Japanese Black Bolt sv11B Booster Box",
    tagline: "Strike with dark energy.",
    description:
      "A full Japanese booster box from the Black Bolt sv11B set. Contains 30 booster packs crackling with dark and electric power, featuring Japanese-exclusive special illustration rares.",
    price: 13000,
    priceDisplay: "£130.00",
    image: "/images/studio.svg",
    contents: [
      "30× Black Bolt sv11B booster packs (10 cards each)",
      "Chance at rare holos, ultra rares, and secret rares",
      "Japanese exclusive artwork and card variants",
    ],
    badge: "New",
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-22",
  },
  {
    id: "japanese-white-flare-sv11w-booster-box",
    slug: "japanese-white-flare-sv11w-booster-box",
    name: "Japanese White Flare sv11W Booster Box",
    tagline: "Blaze with radiant energy.",
    description:
      "A full Japanese booster box from the White Flare sv11W set. Contains 30 booster packs glowing with radiant Pokémon power and stunning Japanese-exclusive artwork.",
    price: 11000,
    priceDisplay: "£110.00",
    image: "/images/mini.svg",
    contents: [
      "30× White Flare sv11W booster packs (10 cards each)",
      "Chance at rare holos, ultra rares, and secret rares",
      "Japanese exclusive artwork and card variants",
    ],
    badge: "New",
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-21",
  },
  {
    id: "japanese-glory-of-team-rocket-sv10-booster-box",
    slug: "japanese-glory-of-team-rocket-sv10-booster-box",
    name: "Japanese The Glory of Team Rocket sv10 Booster Box",
    tagline: "Prepare for trouble — and rare pulls.",
    description:
      "A full Japanese booster box from The Glory of Team Rocket sv10 set, celebrating the iconic villains of the Pokémon world with stunning Japanese artwork. Contains 30 booster packs.",
    price: 13000,
    priceDisplay: "£130.00",
    image: "/images/midnight.svg",
    contents: [
      "30× The Glory of Team Rocket sv10 booster packs (10 cards each)",
      "Chance at Team Rocket rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-20",
  },
  {
    id: "japanese-heatwave-arena-sv9a-booster-box",
    slug: "japanese-heatwave-arena-sv9a-booster-box",
    name: "Japanese Heatwave Arena sv9a Booster Box",
    tagline: "Feel the heat of Japanese battle.",
    description:
      "A full Japanese booster box from the Heatwave Arena sv9a set, featuring intense arena battles and scorching Pokémon power in exclusive Japanese artwork. Contains 30 booster packs.",
    price: 10000,
    priceDisplay: "£100.00",
    image: "/images/studio.svg",
    contents: [
      "30× Heatwave Arena sv9a booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-19",
  },
  {
    id: "japanese-battle-partners-sv9-booster-box",
    slug: "japanese-battle-partners-sv9-booster-box",
    name: "Japanese Battle Partners sv9 Booster Box",
    tagline: "Partner up for rare pulls.",
    description:
      "A full Japanese booster box from the Battle Partners sv9 set, showcasing legendary Pokémon partnerships in vivid Japanese-exclusive artwork. Contains 30 booster packs.",
    price: 8500,
    priceDisplay: "£85.00",
    image: "/images/mini.svg",
    contents: [
      "30× Battle Partners sv9 booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-18",
  },
  {
    id: "japanese-terastal-festival-sv8b-booster-box",
    slug: "japanese-terastal-festival-sv8b-booster-box",
    name: "Japanese Terastal Festival sv8B Booster Box",
    tagline: "Celebrate the Terastal phenomenon.",
    description:
      "A full Japanese booster box from the Terastal Festival sv8B set, honouring the dazzling Terastal transformation with crystalline Japanese-exclusive artwork. Contains 30 booster packs.",
    price: 10500,
    priceDisplay: "£105.00",
    image: "/images/midnight.svg",
    contents: [
      "30× Terastal Festival sv8B booster packs (10 cards each)",
      "Chance at Terastal EX and full-art ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-17",
  },
  {
    id: "japanese-super-electric-breaker-sv8-booster-box",
    slug: "japanese-super-electric-breaker-sv8-booster-box",
    name: "Japanese Super Electric Breaker sv8 Booster Box",
    tagline: "Charge up your Japanese collection.",
    description:
      "A full Japanese booster box from the Super Electric Breaker sv8 set, crackling with Electric-type Pokémon power and electrifying Japanese-exclusive artwork. Contains 30 booster packs.",
    price: 17500,
    priceDisplay: "£175.00",
    image: "/images/studio.svg",
    contents: [
      "30× Super Electric Breaker sv8 booster packs (10 cards each)",
      "Chance at Electric-type rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    badge: "Popular",
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-16",
  },
  {
    id: "japanese-paradise-dragona-sv7a-booster-box",
    slug: "japanese-paradise-dragona-sv7a-booster-box",
    name: "Japanese Paradise Dragona sv7a Booster Box",
    tagline: "Discover a Japanese dragon paradise.",
    description:
      "A full Japanese booster box from the Paradise Dragona sv7a set, celebrating majestic Dragon-type Pokémon in lush paradise-themed Japanese-exclusive artwork. Contains 30 booster packs.",
    price: 7800,
    priceDisplay: "£78.00",
    image: "/images/mini.svg",
    contents: [
      "30× Paradise Dragona sv7a booster packs (10 cards each)",
      "Chance at Dragon-type rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-15",
  },
  {
    id: "japanese-stellar-miracle-sv7-booster-box",
    slug: "japanese-stellar-miracle-sv7-booster-box",
    name: "Japanese Stellar Miracle sv7 Booster Box",
    tagline: "A stellar miracle in every pack.",
    description:
      "A full Japanese booster box from the Stellar Miracle sv7 set, featuring celestial Pokémon and breathtaking Japanese-exclusive star-themed artwork. Contains 30 booster packs.",
    price: 7000,
    priceDisplay: "£70.00",
    image: "/images/midnight.svg",
    contents: [
      "30× Stellar Miracle sv7 booster packs (10 cards each)",
      "Chance at rare holos, ultra rares, and secret rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-14",
  },
  {
    id: "japanese-night-wanderer-sv6a-booster-box",
    slug: "japanese-night-wanderer-sv6a-booster-box",
    name: "Japanese Night Wanderer sv6a Booster Box",
    tagline: "Wander into the night for rare finds.",
    description:
      "A full Japanese booster box from the Night Wanderer sv6a set, exploring moonlit mysteries with Ghost and Dark Pokémon in exclusive Japanese artwork. Contains 30 booster packs.",
    price: 7000,
    priceDisplay: "£70.00",
    image: "/images/studio.svg",
    contents: [
      "30× Night Wanderer sv6a booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-13",
  },
  {
    id: "japanese-mask-of-change-sv6-booster-box",
    slug: "japanese-mask-of-change-sv6-booster-box",
    name: "Japanese Mask of Change sv6 Booster Box",
    tagline: "Change your luck with every pull.",
    description:
      "A full Japanese booster box from the Mask of Change sv6 set, featuring transforming Pokémon in dramatic Japanese-exclusive masked artwork. Contains 30 booster packs.",
    price: 9000,
    priceDisplay: "£90.00",
    image: "/images/mini.svg",
    contents: [
      "30× Mask of Change sv6 booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-12",
  },
  {
    id: "japanese-crimson-haze-sv5a-booster-box",
    slug: "japanese-crimson-haze-sv5a-booster-box",
    name: "Japanese Crimson Haze sv5A Booster Box",
    tagline: "Through the haze, rare Japanese cards await.",
    description:
      "A full Japanese booster box from the Crimson Haze sv5A set, draped in fiery crimson energy with striking Japanese-exclusive Fire and Dragon Pokémon artwork. Contains 30 booster packs.",
    price: 9000,
    priceDisplay: "£90.00",
    image: "/images/midnight.svg",
    contents: [
      "30× Crimson Haze sv5A booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-11",
  },
  {
    id: "japanese-cyber-judge-sv5m-booster-box",
    slug: "japanese-cyber-judge-sv5m-booster-box",
    name: "Japanese Cyber Judge sv5M Booster Box",
    tagline: "Judge your collection wisely.",
    description:
      "A full Japanese booster box from the Cyber Judge sv5M set, featuring futuristic Pokémon in cyberpunk-inspired Japanese-exclusive artwork. Contains 30 booster packs.",
    price: 7000,
    priceDisplay: "£70.00",
    image: "/images/studio.svg",
    contents: [
      "30× Cyber Judge sv5M booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-10",
  },
  {
    id: "japanese-wild-force-sv5k-booster-box",
    slug: "japanese-wild-force-sv5k-booster-box",
    name: "Japanese Wild Force sv5K Booster Box",
    tagline: "Unleash the power of Japanese wild.",
    description:
      "A full Japanese booster box from the Wild Force sv5K set, featuring fierce Pokémon and high-energy battle cards in exclusive Japanese artwork. Contains 30 booster packs.",
    price: 7500,
    priceDisplay: "£75.00",
    image: "/images/mini.svg",
    contents: [
      "30× Wild Force sv5K booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-09",
  },
  {
    id: "japanese-shiny-treasure-sv4a-booster-box",
    slug: "japanese-shiny-treasure-sv4a-booster-box",
    name: "Japanese Shiny Treasure sv4a Booster Box",
    tagline: "Uncover shiny treasures with every pack.",
    description:
      "A full Japanese booster box from the Shiny Treasure sv4a set, packed with shiny Pokémon variants and exclusive Japanese treasure-themed artwork. Contains 30 booster packs.",
    price: 10000,
    priceDisplay: "£100.00",
    image: "/images/midnight.svg",
    contents: [
      "30× Shiny Treasure sv4a booster packs (10 cards each)",
      "Chance at shiny rare holos and ultra rares",
      "Japanese exclusive shiny variants possible",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-08",
  },
  {
    id: "japanese-future-flash-sv4m-booster-box",
    slug: "japanese-future-flash-sv4m-booster-box",
    name: "Japanese Future Flash sv4M Booster Box",
    tagline: "Flash forward to rare pulls.",
    description:
      "A full Japanese booster box from the Future Flash sv4M set, featuring futuristic Pokémon designs in lightning-fast Japanese-exclusive artwork. Contains 30 booster packs.",
    price: 7500,
    priceDisplay: "£75.00",
    image: "/images/studio.svg",
    contents: [
      "30× Future Flash sv4M booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-07",
  },
  {
    id: "japanese-ancient-roar-sv4k-booster-box",
    slug: "japanese-ancient-roar-sv4k-booster-box",
    name: "Japanese Ancient Roar sv4k Booster Box",
    tagline: "Roar into ancient rare territory.",
    description:
      "A full Japanese booster box from the Ancient Roar sv4k set, bringing prehistoric Pokémon to life with ancient-themed Japanese-exclusive artwork. Contains 30 booster packs.",
    price: 6000,
    priceDisplay: "£60.00",
    image: "/images/mini.svg",
    contents: [
      "30× Ancient Roar sv4k booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-06",
  },
  {
    id: "japanese-raging-surf-sv3a-booster-box",
    slug: "japanese-raging-surf-sv3a-booster-box",
    name: "Japanese Raging Surf sv3a Booster Box",
    tagline: "Ride the wave to rare pulls.",
    description:
      "A full Japanese booster box from the Raging Surf sv3a set, featuring Water-type Pokémon riding powerful waves in exclusive Japanese ocean-themed artwork. Contains 30 booster packs.",
    price: 7500,
    priceDisplay: "£75.00",
    image: "/images/midnight.svg",
    contents: [
      "30× Raging Surf sv3a booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-05",
  },
  {
    id: "japanese-ruler-of-the-black-flame-sv3-booster-box",
    slug: "japanese-ruler-of-the-black-flame-sv3-booster-box",
    name: "Japanese Ruler of the Black Flame sv3 Booster Box",
    tagline: "Rule your collection with dark fire.",
    description:
      "A full Japanese booster box from the Ruler of the Black Flame sv3 set, featuring the fearsome Charizard and allies in dramatic Japanese-exclusive dark flame artwork. Contains 30 booster packs.",
    price: 10000,
    priceDisplay: "£100.00",
    image: "/images/studio.svg",
    contents: [
      "30× Ruler of the Black Flame sv3 booster packs (10 cards each)",
      "Chance at rare holos, ultra rares, and secret rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-04",
  },
  {
    id: "japanese-clay-burst-sv2d-booster-box",
    slug: "japanese-clay-burst-sv2d-booster-box",
    name: "Japanese Clay Burst sv2D Booster Box",
    tagline: "Burst through clay for rare finds.",
    description:
      "A full Japanese booster box from the Clay Burst sv2D set, showcasing ancient Pokémon emerging from earthen clay in Japanese-exclusive artistic style. Contains 30 booster packs.",
    price: 8600,
    priceDisplay: "£86.00",
    image: "/images/mini.svg",
    contents: [
      "30× Clay Burst sv2D booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-03",
  },
  {
    id: "japanese-triple-beat-sv1a-booster-box",
    slug: "japanese-triple-beat-sv1a-booster-box",
    name: "Japanese Triple Beat sv1a Booster Box",
    tagline: "Triple your chances of rare pulls.",
    description:
      "A full Japanese booster box from the Triple Beat sv1a set, celebrating triple-threat Pokémon battles in vibrant Japanese-exclusive trio-themed artwork. Contains 30 booster packs.",
    price: 10000,
    priceDisplay: "£100.00",
    image: "/images/midnight.svg",
    contents: [
      "30× Triple Beat sv1a booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-02",
  },
  {
    id: "japanese-violet-ex-sv1v-booster-box",
    slug: "japanese-violet-ex-sv1v-booster-box",
    name: "Japanese Violet EX sv1V Booster Box",
    tagline: "Start your Scarlet & Violet journey.",
    description:
      "A full Japanese booster box from the Violet EX sv1V set, the launch set of the Scarlet & Violet era featuring brand-new EX Pokémon in exclusive Japanese artwork. Contains 30 booster packs.",
    price: 6700,
    priceDisplay: "£67.00",
    image: "/images/studio.svg",
    contents: [
      "30× Violet EX sv1V booster packs (10 cards each)",
      "Chance at EX rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-01",
  },

  // ─── Yu-Gi-Oh! Trading Card Game ───────────────────────────────────────────
  {
    id: "yugioh-infinite-forbidden-booster-box",
    slug: "yugioh-infinite-forbidden-booster-box",
    name: "Yu-Gi-Oh! Infinite Forbidden Booster Box",
    tagline: "Unlock infinite power from the forbidden.",
    description:
      "A full booster box from the Infinite Forbidden (INFI) set. Contains 24 booster packs featuring powerful Forbidden cards and cutting-edge strategies for the modern meta. Ideal for collectors and competitive players alike.",
    price: 7000,
    priceDisplay: "£70.00",
    image: "/images/midnight.svg",
    contents: [
      "24× Infinite Forbidden booster packs (9 cards each)",
      "Chance at Ultra Rare, Secret Rare, and Quarter Century Secret Rare",
      "Modern competitive staples and collector pieces",
    ],
    badge: "New",
    category: "Yu-Gi-Oh! TCG",
    inStock: true,
    createdAt: "2026-04-04",
  },
  {
    id: "yugioh-legacy-of-destruction-booster-box",
    slug: "yugioh-legacy-of-destruction-booster-box",
    name: "Yu-Gi-Oh! Legacy of Destruction Booster Box",
    tagline: "Forge your legacy with every pull.",
    description:
      "A full booster box from the Legacy of Destruction (LEDE) set. Contains 24 booster packs bringing iconic monsters back in bold new forms alongside exciting new archetypes.",
    price: 6500,
    priceDisplay: "£65.00",
    image: "/images/studio.svg",
    contents: [
      "24× Legacy of Destruction booster packs (9 cards each)",
      "Chance at Ultra Rare, Secret Rare, and Quarter Century Secret Rare",
      "Classic and new archetypes in one powerful set",
    ],
    category: "Yu-Gi-Oh! TCG",
    inStock: true,
    createdAt: "2026-04-03",
  },
  {
    id: "yugioh-phantom-nightmare-booster-box",
    slug: "yugioh-phantom-nightmare-booster-box",
    name: "Yu-Gi-Oh! Phantom Nightmare Booster Box",
    tagline: "Face your nightmares and pull your rares.",
    description:
      "A full booster box from the Phantom Nightmare (PHNI) set. Contains 24 booster packs packed with ghostly new monsters and powerful support cards for fan-favourite archetypes.",
    price: 6500,
    priceDisplay: "£65.00",
    image: "/images/midnight.svg",
    contents: [
      "24× Phantom Nightmare booster packs (9 cards each)",
      "Chance at Ultra Rare, Secret Rare, and Quarter Century Secret Rare",
      "Key support for fan-favourite archetypes",
    ],
    badge: "Popular",
    category: "Yu-Gi-Oh! TCG",
    inStock: true,
    createdAt: "2026-04-02",
  },
  {
    id: "yugioh-age-of-overlord-booster-box",
    slug: "yugioh-age-of-overlord-booster-box",
    name: "Yu-Gi-Oh! Age of Overlord Booster Box",
    tagline: "Rise to overlord status with every pull.",
    description:
      "A full booster box from the Age of Overlord (AGOV) set. Contains 24 booster packs featuring the debut of the powerful Purrely and Kashtira archetypes alongside game-changing spell and trap support.",
    price: 6000,
    priceDisplay: "£60.00",
    image: "/images/studio.svg",
    contents: [
      "24× Age of Overlord booster packs (9 cards each)",
      "Chance at Ultra Rare, Secret Rare, and Quarter Century Secret Rare",
      "Debut of multiple dominant meta archetypes",
    ],
    category: "Yu-Gi-Oh! TCG",
    inStock: true,
    createdAt: "2026-04-01",
  },
  {
    id: "yugioh-wild-survivors-booster-box",
    slug: "yugioh-wild-survivors-booster-box",
    name: "Yu-Gi-Oh! Wild Survivors Booster Box",
    tagline: "Survive the wild and claim your rares.",
    description:
      "A full booster box from the Wild Survivors (WISU) set. Contains 24 booster packs featuring bold new Link, Synchro, and XYZ monsters alongside electrifying support for existing fan-favourite strategies.",
    price: 6000,
    priceDisplay: "£60.00",
    image: "/images/mini.svg",
    contents: [
      "24× Wild Survivors booster packs (9 cards each)",
      "Chance at Ultra Rare, Secret Rare, and Collectors Rare",
      "Powerful new cards for multiple popular strategies",
    ],
    category: "Yu-Gi-Oh! TCG",
    inStock: true,
    createdAt: "2026-03-31",
  },

  // ─── Other TCG ─────────────────────────────────────────────────────────────
  {
    id: "mtg-bloomburrow-draft-booster-box",
    slug: "mtg-bloomburrow-draft-booster-box",
    name: "Magic: The Gathering — Bloomburrow Draft Booster Box",
    tagline: "A world of tiny creatures, giant adventures.",
    description:
      "A full draft booster box from Magic: The Gathering's Bloomburrow set — a whimsical woodland plane populated entirely by anthropomorphic animals. Contains 36 draft booster packs, perfect for draft events or set collection.",
    price: 10000,
    priceDisplay: "£100.00",
    image: "/images/studio.svg",
    contents: [
      "36× Bloomburrow draft booster packs (14 cards each)",
      "1 guaranteed rare or mythic rare per pack",
      "Full-art basic lands possible",
      "Showcase and special treatment variants possible",
    ],
    badge: "Popular",
    category: "Other TCG",
    inStock: true,
    createdAt: "2026-04-04",
  },
  {
    id: "mtg-duskmourn-draft-booster-box",
    slug: "mtg-duskmourn-draft-booster-box",
    name: "Magic: The Gathering — Duskmourn Draft Booster Box",
    tagline: "The house always wins — until you pull a mythic.",
    description:
      "A full draft booster box from Magic: The Gathering's Duskmourn: House of Horror set — a gothic horror plane filled with cursed mansions and terrifying creatures. Contains 36 draft booster packs.",
    price: 10000,
    priceDisplay: "£100.00",
    image: "/images/midnight.svg",
    contents: [
      "36× Duskmourn draft booster packs (14 cards each)",
      "1 guaranteed rare or mythic rare per pack",
      "Showcase horror-frame variants possible",
      "Double-faced cards included",
    ],
    category: "Other TCG",
    inStock: true,
    createdAt: "2026-04-03",
  },
  {
    id: "one-piece-op09-booster-box",
    slug: "one-piece-op09-booster-box",
    name: "One Piece Card Game — OP-09 Emperors in the New World Booster Box",
    tagline: "Set sail for the Grand Line's greatest pulls.",
    description:
      "A full booster box from the One Piece Card Game OP-09 Emperors in the New World set. Features the fearsome Emperors of the Sea in stunning full-art illustrations. Contains 24 booster packs.",
    price: 6500,
    priceDisplay: "£65.00",
    image: "/images/studio.svg",
    contents: [
      "24× OP-09 Emperors in the New World booster packs (12 cards each)",
      "Chance at Leader, Secret Rare, and Special Rare cards",
      "Full-art alternate art Leader cards possible",
    ],
    badge: "New",
    category: "Other TCG",
    inStock: true,
    createdAt: "2026-04-02",
  },
  {
    id: "one-piece-op08-booster-box",
    slug: "one-piece-op08-booster-box",
    name: "One Piece Card Game — OP-08 Two Legends Booster Box",
    tagline: "Two legendary captains, infinite pulls.",
    description:
      "A full booster box from the One Piece Card Game OP-08 Two Legends set, celebrating two iconic captains in a clash of legendary power. Contains 24 booster packs featuring stunning alternate art cards.",
    price: 6500,
    priceDisplay: "£65.00",
    image: "/images/midnight.svg",
    contents: [
      "24× OP-08 Two Legends booster packs (12 cards each)",
      "Chance at Secret Rare and Special Rare cards",
      "Full-art Leader and Character cards possible",
    ],
    category: "Other TCG",
    inStock: true,
    createdAt: "2026-04-01",
  },
  {
    id: "lorcana-azurite-sea-booster-box",
    slug: "lorcana-azurite-sea-booster-box",
    name: "Disney Lorcana — Azurite Sea Booster Box",
    tagline: "Dive deep for rare Disney glimmers.",
    description:
      "A full booster box from Disney Lorcana's Azurite Sea set — an underwater realm of mystery and wonder filled with beloved Disney characters reimagined as oceanic glimmers. Contains 24 booster packs.",
    price: 8500,
    priceDisplay: "£85.00",
    image: "/images/studio.svg",
    contents: [
      "24× Azurite Sea booster packs (12 cards each)",
      "1 guaranteed foil card per pack",
      "Chance at Enchanted rarity cards",
      "Alternate art Character and Action cards possible",
    ],
    badge: "New",
    category: "Other TCG",
    inStock: true,
    createdAt: "2026-03-31",
  },
  {
    id: "digimon-ex-06-booster-box",
    slug: "digimon-ex-06-booster-box",
    name: "Digimon Card Game — EX-06 Infernal Ascension Booster Box",
    tagline: "Ascend to new Digivolution heights.",
    description:
      "A full booster box from the Digimon Card Game EX-06 Infernal Ascension set, featuring powerful demon lord Digimon and blazing new Digivolution chains. Contains 24 booster packs.",
    price: 5500,
    priceDisplay: "£55.00",
    image: "/images/midnight.svg",
    contents: [
      "24× EX-06 Infernal Ascension booster packs (12 cards each)",
      "Chance at Rare, Super Rare, and Secret Rare cards",
      "Parallel alternate art variants possible",
    ],
    category: "Other TCG",
    inStock: true,
    createdAt: "2026-03-30",
  },
  {
    id: "star-wars-unlimited-twilight-of-republic-booster-box",
    slug: "star-wars-unlimited-twilight-of-republic-booster-box",
    name: "Star Wars: Unlimited — Twilight of the Republic Booster Box",
    tagline: "The Republic's twilight begins with your pull.",
    description:
      "A full booster box from Star Wars: Unlimited's Twilight of the Republic set, set during the Clone Wars era and featuring iconic heroes and villains on both sides of the conflict. Contains 24 booster packs.",
    price: 7500,
    priceDisplay: "£75.00",
    image: "/images/studio.svg",
    contents: [
      "24× Twilight of the Republic booster packs (16 cards each)",
      "1 guaranteed rare or higher per pack",
      "Foil, showcase, and Hyperspace variants possible",
    ],
    category: "Other TCG",
    inStock: true,
    createdAt: "2026-03-29",
  },
  {
    id: "dragon-ball-super-fw-booster-box",
    slug: "dragon-ball-super-fw-booster-box",
    name: "Dragon Ball Super — Fusion World Booster Box",
    tagline: "Power levels beyond imagination.",
    description:
      "A full booster box from the Dragon Ball Super Card Game Fusion World expansion. Fusing power levels never seen before with fan-favourite characters and dramatic art. Contains 24 booster packs.",
    price: 5000,
    priceDisplay: "£50.00",
    image: "/images/midnight.svg",
    contents: [
      "24× Fusion World booster packs (12 cards each)",
      "1 guaranteed Rare or higher per pack",
      "Chance at Special Rare and Secret Rare",
      "Parallel art variants possible",
    ],
    category: "Other TCG",
    inStock: true,
    createdAt: "2026-03-28",
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}
