export interface Product {
  id: string;
  slug: string;
  name: string;
  tagline: string;
  description: string;
  price: number; // in cents
  priceDisplay: string;
  image: string;
  stripePrice?: string;
  contents: string[];
  badge?: string;
  /** Category also doubles as the TCG game name for TCG products */
  category: string;
  inStock: boolean;
  createdAt: string; // ISO date string for "newest" sort
}

export const products: Product[] = [
  {
    id: "mini",
    slug: "mini",
    name: "Mini Crate",
    tagline: "A gentle introduction to the unknown.",
    description:
      "The Mini Crate holds one carefully curated mystery figure. Perfect for first-timers or those who savour small surprises. Each figure is sourced from premium collectible series — unwrapped slowly, one at a time.",
    price: 1499,
    priceDisplay: "$14.99",
    image: "/images/mini.svg",
    contents: ["1 mystery collectible figure", "Branded tissue wrap", "Collector card"],
    badge: "Starter",
    category: "Mystery Box",
    inStock: true,
    createdAt: "2025-01-20",
  },
  {
    id: "studio",
    slug: "studio",
    name: "Studio Crate",
    tagline: "The standard bearer of mystery.",
    description:
      "Three figures, three moments of discovery. The Studio Crate is our most popular tier — a balanced unboxing ritual that feels complete. Expect variety, quality, and at least one rare.",
    price: 3499,
    priceDisplay: "$34.99",
    image: "/images/studio.svg",
    contents: [
      "3 mystery collectible figures",
      "1 guaranteed rare figure",
      "Branded tissue wrap",
      "2x collector cards",
      "Sticker set",
    ],
    badge: "Popular",
    category: "Mystery Box",
    inStock: true,
    createdAt: "2025-01-20",
  },
  {
    id: "midnight",
    slug: "midnight",
    name: "Midnight Crate",
    tagline: "For those who embrace the premium unknown.",
    description:
      "Six figures. Two guaranteed rares. One ultra-rare possibility. The Midnight Crate is our most immersive experience — delivered in a matte black box with gold foil. Slow down. Breathe. Open.",
    price: 6999,
    priceDisplay: "$69.99",
    image: "/images/midnight.svg",
    contents: [
      "6 mystery collectible figures",
      "2 guaranteed rare figures",
      "1 chance at ultra-rare",
      "Matte black gift box with gold foil",
      "Premium tissue wrap",
      "4x collector cards",
      "Sticker set",
      "Exclusive Noir Crates bookmark",
    ],
    badge: "Premium",
    category: "Premium",
    inStock: true,
    createdAt: "2025-01-20",
  },
  {
    id: "labubu-forest",
    slug: "labubu-forest",
    name: "Forest Series Vol.1",
    tagline: "Tiny woodland creatures, infinite charm.",
    description:
      "Each blind box in the Forest Series contains one of twelve woodland-themed collectible figures. Soft palettes, intricate detail, and one hidden chase variant make every unboxing a delight.",
    price: 2299,
    priceDisplay: "$22.99",
    image: "/images/studio.svg",
    contents: [
      "1 mystery forest figure (1 of 12 designs)",
      "1 secret chase variant possible",
      "Collector card",
    ],
    badge: "New",
    category: "Series",
    inStock: true,
    createdAt: "2025-01-15",
  },
  {
    id: "neon-pop",
    slug: "neon-pop",
    name: "Neon Pop Vol.2",
    tagline: "Bold colour, bold surprises.",
    description:
      "The second volume of our Neon Pop series brings ten vibrant characters inspired by midnight city lights. Glow-in-the-dark variants are hidden throughout the run.",
    price: 1999,
    priceDisplay: "$19.99",
    image: "/images/mini.svg",
    contents: [
      "1 mystery neon figure (1 of 10 designs)",
      "Glow-in-the-dark variant possible",
      "Collector card",
    ],
    category: "Series",
    inStock: true,
    createdAt: "2025-01-10",
  },
  {
    id: "dark-matter",
    slug: "dark-matter",
    name: "Dark Matter Vol.1",
    tagline: "Limited. Cosmic. Unmissable.",
    description:
      "A limited-edition run of nine deep-space themed figures with metallic finishes. Once this batch sells out, it won't return. Includes one exclusive ultra-rare holographic variant.",
    price: 4499,
    priceDisplay: "$44.99",
    image: "/images/midnight.svg",
    contents: [
      "1 mystery cosmic figure (1 of 9 designs)",
      "Metallic finish on all variants",
      "1 holographic ultra-rare possible",
      "Premium collector card",
    ],
    badge: "Limited",
    category: "Limited Edition",
    inStock: true,
    createdAt: "2024-12-20",
  },
  {
    id: "crystal-dream",
    slug: "crystal-dream",
    name: "Crystal Dream",
    tagline: "Translucent wonder in every box.",
    description:
      "Eight delicate crystal-clear figures, each hand-cast in tinted resin. A meditative unboxing experience — slow, tactile, and deeply satisfying.",
    price: 2799,
    priceDisplay: "$27.99",
    image: "/images/mini.svg",
    contents: [
      "1 mystery crystal figure (1 of 8 designs)",
      "Hand-cast tinted resin",
      "Collector card",
      "Branded tissue wrap",
    ],
    category: "Mystery Box",
    inStock: true,
    createdAt: "2024-12-15",
  },
  {
    id: "sakura-bloom",
    slug: "sakura-bloom",
    name: "Sakura Bloom",
    tagline: "Spring in every box — while supplies last.",
    description:
      "Inspired by cherry-blossom season, the Sakura Bloom series features soft pinks, whites, and blush figures with petal-shaped bases. This run has sold out — join the waitlist for the next drop.",
    price: 2499,
    priceDisplay: "$24.99",
    image: "/images/studio.svg",
    contents: [
      "1 mystery sakura figure (1 of 8 designs)",
      "Petal-shaped base included",
      "Collector card",
    ],
    category: "Series",
    inStock: false,
    createdAt: "2024-12-01",
  },
  {
    id: "stellar-night",
    slug: "stellar-night",
    name: "Stellar Night",
    tagline: "Premium figures for the dedicated collector.",
    description:
      "Our premium Stellar Night collection features larger, more detailed figures with hand-painted accents. Six designs, each in a gift-grade matte box. A collector's showcase piece.",
    price: 3299,
    priceDisplay: "$32.99",
    image: "/images/midnight.svg",
    contents: [
      "1 premium stellar figure (1 of 6 designs)",
      "Hand-painted accents",
      "Matte gift box",
      "Certificate of design",
    ],
    badge: "Premium",
    category: "Premium",
    inStock: true,
    createdAt: "2024-11-20",
  },
  {
    id: "mossy-garden",
    slug: "mossy-garden",
    name: "Mossy Garden",
    tagline: "Quiet, earthy, and full of life.",
    description:
      "Ten peaceful garden-themed figures in muted greens and terracottas. Perfect as desk companions or shelf art. The Mossy Garden series pairs beautifully with our Mini Crate.",
    price: 1799,
    priceDisplay: "$17.99",
    image: "/images/mini.svg",
    contents: [
      "1 mystery garden figure (1 of 10 designs)",
      "Collector card",
      "Branded tissue wrap",
    ],
    category: "Mystery Box",
    inStock: true,
    createdAt: "2024-11-10",
  },

  // ─── Blind Boxes ───────────────────────────────────────────────────────────
  {
    id: "urban-nights-blind-box",
    slug: "urban-nights-blind-box",
    name: "Urban Nights Blind Box",
    tagline: "One figure. Infinite city vibes.",
    description:
      "Ten urban-inspired collectible figures capture the energy of city nights — neon signs, rooftop views, and street-level grit. Each single-figure blind box reveals one of ten designs, with one hidden limited chase variant.",
    price: 1299,
    priceDisplay: "$12.99",
    image: "/images/mini.svg",
    contents: [
      "1 mystery urban figure (1 of 10 designs)",
      "1 limited chase variant possible",
      "Collector card",
    ],
    badge: "New",
    category: "Blind Box",
    inStock: true,
    createdAt: "2025-02-15",
  },
  {
    id: "neon-dreamscape-blind-box",
    slug: "neon-dreamscape-blind-box",
    name: "Neon Dreamscape Blind Box",
    tagline: "Dream in colour, wake in surprise.",
    description:
      "Eight surreal dreamscape figures rendered in vivid neons and pastels. A single blind box holds one mystery figure — a pure unboxing moment, nothing more, nothing less.",
    price: 999,
    priceDisplay: "$9.99",
    image: "/images/mini.svg",
    contents: [
      "1 mystery dreamscape figure (1 of 8 designs)",
      "Collector card",
    ],
    category: "Blind Box",
    inStock: true,
    createdAt: "2025-02-10",
  },
  {
    id: "retro-arcade-blind-box",
    slug: "retro-arcade-blind-box",
    name: "Retro Arcade Blind Box",
    tagline: "Insert coin. Receive joy.",
    description:
      "Twelve pixel-art-inspired figures celebrate the golden age of arcades. Bold shapes, retro colours, and one secret rare variant hiding in the set.",
    price: 1199,
    priceDisplay: "$11.99",
    image: "/images/studio.svg",
    contents: [
      "1 mystery retro figure (1 of 12 designs)",
      "1 secret rare possible",
      "Collector card",
    ],
    category: "Blind Box",
    inStock: true,
    createdAt: "2025-02-05",
  },
  {
    id: "celestial-bloom-blind-box",
    slug: "celestial-bloom-blind-box",
    name: "Celestial Bloom Blind Box",
    tagline: "Stars blooming in every box.",
    description:
      "Eight celestial garden figures blend cosmic imagery with delicate florals. Soft metallics, fine detailing, and a meditative single-figure unboxing experience.",
    price: 1399,
    priceDisplay: "$13.99",
    image: "/images/studio.svg",
    contents: [
      "1 mystery celestial figure (1 of 8 designs)",
      "Collector card",
      "Branded tissue wrap",
    ],
    badge: "Popular",
    category: "Blind Box",
    inStock: true,
    createdAt: "2025-01-25",
  },

  // ─── Trading Card Games ────────────────────────────────────────────────────
  // ── Pokémon Japanese Booster Boxes ─────────────────────────────────────────
  {
    id: "japanese-ninja-spinner-booster-box",
    slug: "japanese-ninja-spinner-booster-box",
    name: "Japanese Ninja Spinner Booster Box",
    tagline: "Spin your way to rare Japanese pulls.",
    description:
      "A full Japanese booster box from the Ninja Spinner set. Contains 30 booster packs bursting with ninja-themed Pokémon and exclusive Japanese artwork not found in Western releases.",
    price: 9000,
    priceDisplay: "£90.00",
    image: "/images/studio.svg",
    contents: [
      "30× Ninja Spinner booster packs (10 cards each)",
      "Chance at rare holos, ultra rares, and secret rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-28",
  },
  {
    id: "japanese-mega-munikis-zero-booster-box",
    slug: "japanese-mega-munikis-zero-booster-box",
    name: "Japanese MEGA Munikis Zero Booster Box",
    tagline: "Zero limits on rare pulls.",
    description:
      "A full Japanese booster box from the MEGA Munikis Zero set. Contains 30 booster packs featuring powerful MEGA Pokémon and stunning Japanese-exclusive special art.",
    price: 8000,
    priceDisplay: "£80.00",
    image: "/images/mini.svg",
    contents: [
      "30× MEGA Munikis Zero booster packs (10 cards each)",
      "Chance at MEGA EX and full-art ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-27",
  },
  {
    id: "japanese-mega-dream-ex-booster-box",
    slug: "japanese-mega-dream-ex-booster-box",
    name: "Japanese MEGA Dream ex Booster Box",
    tagline: "Dream big with every Japanese pull.",
    description:
      "A full Japanese booster box from the MEGA Dream ex set, packed with powerful EX Pokémon cards and stunning Japanese-exclusive special art. Contains 30 booster packs ideal for collectors.",
    price: 11600,
    priceDisplay: "£116.00",
    image: "/images/midnight.svg",
    contents: [
      "30× MEGA Dream ex booster packs (10 cards each)",
      "Chance at EX and full-art ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-26",
  },
  {
    id: "japanese-mega-inferno-x-booster-box",
    slug: "japanese-mega-inferno-x-booster-box",
    name: "Japanese MEGA Inferno X Booster Box",
    tagline: "Feel the blazing heat of MEGA power.",
    description:
      "A full Japanese booster box from the MEGA Inferno X set, igniting your collection with fierce Fire-type Pokémon and exclusive Japanese artwork. Contains 30 booster packs of raw power.",
    price: 11500,
    priceDisplay: "£115.00",
    image: "/images/studio.svg",
    contents: [
      "30× MEGA Inferno X booster packs (10 cards each)",
      "Chance at MEGA EX and full-art ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-25",
  },
  {
    id: "japanese-mega-symphonia-booster-box",
    slug: "japanese-mega-symphonia-booster-box",
    name: "Japanese MEGA Symphonia Booster Box",
    tagline: "A symphony of rare pulls.",
    description:
      "A full Japanese booster box from the MEGA Symphonia set, celebrating harmonious Pokémon battles and stunning orchestral-themed Japanese artwork. Contains 30 booster packs.",
    price: 8500,
    priceDisplay: "£85.00",
    image: "/images/mini.svg",
    contents: [
      "30× MEGA Symphonia booster packs (10 cards each)",
      "Chance at MEGA EX and full-art ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-24",
  },
  {
    id: "japanese-mega-brave-booster-box",
    slug: "japanese-mega-brave-booster-box",
    name: "Japanese MEGA Brave Booster Box",
    tagline: "Be brave, pull rare.",
    description:
      "A full Japanese booster box from the MEGA Brave set, honouring the bravest Pokémon in bold Japanese artwork. Contains 30 booster packs packed with powerful MEGA cards.",
    price: 8500,
    priceDisplay: "£85.00",
    image: "/images/midnight.svg",
    contents: [
      "30× MEGA Brave booster packs (10 cards each)",
      "Chance at MEGA EX and full-art ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-23",
  },
  {
    id: "japanese-black-bolt-sv11b-booster-box",
    slug: "japanese-black-bolt-sv11b-booster-box",
    name: "Japanese Black Bolt sv11B Booster Box",
    tagline: "Strike with dark energy.",
    description:
      "A full Japanese booster box from the Black Bolt sv11B set. Contains 30 booster packs crackling with dark and electric power, featuring Japanese-exclusive special illustration rares.",
    price: 13000,
    priceDisplay: "£130.00",
    image: "/images/studio.svg",
    contents: [
      "30× Black Bolt sv11B booster packs (10 cards each)",
      "Chance at rare holos, ultra rares, and secret rares",
      "Japanese exclusive artwork and card variants",
    ],
    badge: "New",
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-22",
  },
  {
    id: "japanese-white-flare-sv11w-booster-box",
    slug: "japanese-white-flare-sv11w-booster-box",
    name: "Japanese White Flare sv11W Booster Box",
    tagline: "Blaze with radiant energy.",
    description:
      "A full Japanese booster box from the White Flare sv11W set. Contains 30 booster packs glowing with radiant Pokémon power and stunning Japanese-exclusive artwork.",
    price: 11000,
    priceDisplay: "£110.00",
    image: "/images/mini.svg",
    contents: [
      "30× White Flare sv11W booster packs (10 cards each)",
      "Chance at rare holos, ultra rares, and secret rares",
      "Japanese exclusive artwork and card variants",
    ],
    badge: "New",
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-21",
  },
  {
    id: "japanese-glory-of-team-rocket-sv10-booster-box",
    slug: "japanese-glory-of-team-rocket-sv10-booster-box",
    name: "Japanese The Glory of Team Rocket sv10 Booster Box",
    tagline: "Prepare for trouble — and rare pulls.",
    description:
      "A full Japanese booster box from The Glory of Team Rocket sv10 set, celebrating the iconic villains of the Pokémon world with stunning Japanese artwork. Contains 30 booster packs.",
    price: 13000,
    priceDisplay: "£130.00",
    image: "/images/midnight.svg",
    contents: [
      "30× The Glory of Team Rocket sv10 booster packs (10 cards each)",
      "Chance at Team Rocket rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-20",
  },
  {
    id: "japanese-heatwave-arena-sv9a-booster-box",
    slug: "japanese-heatwave-arena-sv9a-booster-box",
    name: "Japanese Heatwave Arena sv9a Booster Box",
    tagline: "Feel the heat of Japanese battle.",
    description:
      "A full Japanese booster box from the Heatwave Arena sv9a set, featuring intense arena battles and scorching Pokémon power in exclusive Japanese artwork. Contains 30 booster packs.",
    price: 10000,
    priceDisplay: "£100.00",
    image: "/images/studio.svg",
    contents: [
      "30× Heatwave Arena sv9a booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-19",
  },
  {
    id: "japanese-battle-partners-sv9-booster-box",
    slug: "japanese-battle-partners-sv9-booster-box",
    name: "Japanese Battle Partners sv9 Booster Box",
    tagline: "Partner up for rare pulls.",
    description:
      "A full Japanese booster box from the Battle Partners sv9 set, showcasing legendary Pokémon partnerships in vivid Japanese-exclusive artwork. Contains 30 booster packs.",
    price: 8500,
    priceDisplay: "£85.00",
    image: "/images/mini.svg",
    contents: [
      "30× Battle Partners sv9 booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-18",
  },
  {
    id: "japanese-terastal-festival-sv8b-booster-box",
    slug: "japanese-terastal-festival-sv8b-booster-box",
    name: "Japanese Terastal Festival sv8B Booster Box",
    tagline: "Celebrate the Terastal phenomenon.",
    description:
      "A full Japanese booster box from the Terastal Festival sv8B set, honouring the dazzling Terastal transformation with crystalline Japanese-exclusive artwork. Contains 30 booster packs.",
    price: 10500,
    priceDisplay: "£105.00",
    image: "/images/midnight.svg",
    contents: [
      "30× Terastal Festival sv8B booster packs (10 cards each)",
      "Chance at Terastal EX and full-art ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-17",
  },
  {
    id: "japanese-super-electric-breaker-sv8-booster-box",
    slug: "japanese-super-electric-breaker-sv8-booster-box",
    name: "Japanese Super Electric Breaker sv8 Booster Box",
    tagline: "Charge up your Japanese collection.",
    description:
      "A full Japanese booster box from the Super Electric Breaker sv8 set, crackling with Electric-type Pokémon power and electrifying Japanese-exclusive artwork. Contains 30 booster packs.",
    price: 17500,
    priceDisplay: "£175.00",
    image: "/images/studio.svg",
    contents: [
      "30× Super Electric Breaker sv8 booster packs (10 cards each)",
      "Chance at Electric-type rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    badge: "Popular",
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-16",
  },
  {
    id: "japanese-paradise-dragona-sv7a-booster-box",
    slug: "japanese-paradise-dragona-sv7a-booster-box",
    name: "Japanese Paradise Dragona sv7a Booster Box",
    tagline: "Discover a Japanese dragon paradise.",
    description:
      "A full Japanese booster box from the Paradise Dragona sv7a set, celebrating majestic Dragon-type Pokémon in lush paradise-themed Japanese-exclusive artwork. Contains 30 booster packs.",
    price: 7800,
    priceDisplay: "£78.00",
    image: "/images/mini.svg",
    contents: [
      "30× Paradise Dragona sv7a booster packs (10 cards each)",
      "Chance at Dragon-type rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-15",
  },
  {
    id: "japanese-stellar-miracle-sv7-booster-box",
    slug: "japanese-stellar-miracle-sv7-booster-box",
    name: "Japanese Stellar Miracle sv7 Booster Box",
    tagline: "A stellar miracle in every pack.",
    description:
      "A full Japanese booster box from the Stellar Miracle sv7 set, featuring celestial Pokémon and breathtaking Japanese-exclusive star-themed artwork. Contains 30 booster packs.",
    price: 7000,
    priceDisplay: "£70.00",
    image: "/images/midnight.svg",
    contents: [
      "30× Stellar Miracle sv7 booster packs (10 cards each)",
      "Chance at rare holos, ultra rares, and secret rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-14",
  },
  {
    id: "japanese-night-wanderer-sv6a-booster-box",
    slug: "japanese-night-wanderer-sv6a-booster-box",
    name: "Japanese Night Wanderer sv6a Booster Box",
    tagline: "Wander into the night for rare finds.",
    description:
      "A full Japanese booster box from the Night Wanderer sv6a set, exploring moonlit mysteries with Ghost and Dark Pokémon in exclusive Japanese artwork. Contains 30 booster packs.",
    price: 7000,
    priceDisplay: "£70.00",
    image: "/images/studio.svg",
    contents: [
      "30× Night Wanderer sv6a booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-13",
  },
  {
    id: "japanese-mask-of-change-sv6-booster-box",
    slug: "japanese-mask-of-change-sv6-booster-box",
    name: "Japanese Mask of Change sv6 Booster Box",
    tagline: "Change your luck with every pull.",
    description:
      "A full Japanese booster box from the Mask of Change sv6 set, featuring transforming Pokémon in dramatic Japanese-exclusive masked artwork. Contains 30 booster packs.",
    price: 9000,
    priceDisplay: "£90.00",
    image: "/images/mini.svg",
    contents: [
      "30× Mask of Change sv6 booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-12",
  },
  {
    id: "japanese-crimson-haze-sv5a-booster-box",
    slug: "japanese-crimson-haze-sv5a-booster-box",
    name: "Japanese Crimson Haze sv5A Booster Box",
    tagline: "Through the haze, rare Japanese cards await.",
    description:
      "A full Japanese booster box from the Crimson Haze sv5A set, draped in fiery crimson energy with striking Japanese-exclusive Fire and Dragon Pokémon artwork. Contains 30 booster packs.",
    price: 9000,
    priceDisplay: "£90.00",
    image: "/images/midnight.svg",
    contents: [
      "30× Crimson Haze sv5A booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-11",
  },
  {
    id: "japanese-cyber-judge-sv5m-booster-box",
    slug: "japanese-cyber-judge-sv5m-booster-box",
    name: "Japanese Cyber Judge sv5M Booster Box",
    tagline: "Judge your collection wisely.",
    description:
      "A full Japanese booster box from the Cyber Judge sv5M set, featuring futuristic Pokémon in cyberpunk-inspired Japanese-exclusive artwork. Contains 30 booster packs.",
    price: 7000,
    priceDisplay: "£70.00",
    image: "/images/studio.svg",
    contents: [
      "30× Cyber Judge sv5M booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-10",
  },
  {
    id: "japanese-wild-force-sv5k-booster-box",
    slug: "japanese-wild-force-sv5k-booster-box",
    name: "Japanese Wild Force sv5K Booster Box",
    tagline: "Unleash the power of Japanese wild.",
    description:
      "A full Japanese booster box from the Wild Force sv5K set, featuring fierce Pokémon and high-energy battle cards in exclusive Japanese artwork. Contains 30 booster packs.",
    price: 7500,
    priceDisplay: "£75.00",
    image: "/images/mini.svg",
    contents: [
      "30× Wild Force sv5K booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-09",
  },
  {
    id: "japanese-shiny-treasure-sv4a-booster-box",
    slug: "japanese-shiny-treasure-sv4a-booster-box",
    name: "Japanese Shiny Treasure sv4a Booster Box",
    tagline: "Uncover shiny treasures with every pack.",
    description:
      "A full Japanese booster box from the Shiny Treasure sv4a set, packed with shiny Pokémon variants and exclusive Japanese treasure-themed artwork. Contains 30 booster packs.",
    price: 10000,
    priceDisplay: "£100.00",
    image: "/images/midnight.svg",
    contents: [
      "30× Shiny Treasure sv4a booster packs (10 cards each)",
      "Chance at shiny rare holos and ultra rares",
      "Japanese exclusive shiny variants possible",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-08",
  },
  {
    id: "japanese-future-flash-sv4m-booster-box",
    slug: "japanese-future-flash-sv4m-booster-box",
    name: "Japanese Future Flash sv4M Booster Box",
    tagline: "Flash forward to rare pulls.",
    description:
      "A full Japanese booster box from the Future Flash sv4M set, featuring futuristic Pokémon designs in lightning-fast Japanese-exclusive artwork. Contains 30 booster packs.",
    price: 7500,
    priceDisplay: "£75.00",
    image: "/images/studio.svg",
    contents: [
      "30× Future Flash sv4M booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-07",
  },
  {
    id: "japanese-ancient-roar-sv4k-booster-box",
    slug: "japanese-ancient-roar-sv4k-booster-box",
    name: "Japanese Ancient Roar sv4k Booster Box",
    tagline: "Roar into ancient rare territory.",
    description:
      "A full Japanese booster box from the Ancient Roar sv4k set, bringing prehistoric Pokémon to life with ancient-themed Japanese-exclusive artwork. Contains 30 booster packs.",
    price: 6000,
    priceDisplay: "£60.00",
    image: "/images/mini.svg",
    contents: [
      "30× Ancient Roar sv4k booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-06",
  },
  {
    id: "japanese-raging-surf-sv3a-booster-box",
    slug: "japanese-raging-surf-sv3a-booster-box",
    name: "Japanese Raging Surf sv3a Booster Box",
    tagline: "Ride the wave to rare pulls.",
    description:
      "A full Japanese booster box from the Raging Surf sv3a set, featuring Water-type Pokémon riding powerful waves in exclusive Japanese ocean-themed artwork. Contains 30 booster packs.",
    price: 7500,
    priceDisplay: "£75.00",
    image: "/images/midnight.svg",
    contents: [
      "30× Raging Surf sv3a booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-05",
  },
  {
    id: "japanese-ruler-of-the-black-flame-sv3-booster-box",
    slug: "japanese-ruler-of-the-black-flame-sv3-booster-box",
    name: "Japanese Ruler of the Black Flame sv3 Booster Box",
    tagline: "Rule your collection with dark fire.",
    description:
      "A full Japanese booster box from the Ruler of the Black Flame sv3 set, featuring the fearsome Charizard and allies in dramatic Japanese-exclusive dark flame artwork. Contains 30 booster packs.",
    price: 10000,
    priceDisplay: "£100.00",
    image: "/images/studio.svg",
    contents: [
      "30× Ruler of the Black Flame sv3 booster packs (10 cards each)",
      "Chance at rare holos, ultra rares, and secret rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-04",
  },
  {
    id: "japanese-clay-burst-sv2d-booster-box",
    slug: "japanese-clay-burst-sv2d-booster-box",
    name: "Japanese Clay Burst sv2D Booster Box",
    tagline: "Burst through clay for rare finds.",
    description:
      "A full Japanese booster box from the Clay Burst sv2D set, showcasing ancient Pokémon emerging from earthen clay in Japanese-exclusive artistic style. Contains 30 booster packs.",
    price: 8600,
    priceDisplay: "£86.00",
    image: "/images/mini.svg",
    contents: [
      "30× Clay Burst sv2D booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-03",
  },
  {
    id: "japanese-triple-beat-sv1a-booster-box",
    slug: "japanese-triple-beat-sv1a-booster-box",
    name: "Japanese Triple Beat sv1a Booster Box",
    tagline: "Triple your chances of rare pulls.",
    description:
      "A full Japanese booster box from the Triple Beat sv1a set, celebrating triple-threat Pokémon battles in vibrant Japanese-exclusive trio-themed artwork. Contains 30 booster packs.",
    price: 10000,
    priceDisplay: "£100.00",
    image: "/images/midnight.svg",
    contents: [
      "30× Triple Beat sv1a booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-02",
  },
  {
    id: "japanese-violet-ex-sv1v-booster-box",
    slug: "japanese-violet-ex-sv1v-booster-box",
    name: "Japanese Violet EX sv1V Booster Box",
    tagline: "Start your Scarlet & Violet journey.",
    description:
      "A full Japanese booster box from the Violet EX sv1V set, the launch set of the Scarlet & Violet era featuring brand-new EX Pokémon in exclusive Japanese artwork. Contains 30 booster packs.",
    price: 6700,
    priceDisplay: "£67.00",
    image: "/images/studio.svg",
    contents: [
      "30× Violet EX sv1V booster packs (10 cards each)",
      "Chance at EX rare holos and ultra rares",
      "Japanese exclusive artwork and card variants",
    ],
    category: "Pokémon Japanese Booster Boxes",
    inStock: true,
    createdAt: "2026-03-01",
  },
  {
    id: "magic-draft-booster",
    slug: "magic-draft-booster",
    name: "Magic: The Gathering Draft Booster",
    tagline: "Build your deck. Rule the battlefield.",
    description:
      "One draft booster pack from the latest Magic: The Gathering expansion. Contains 15 cards including one guaranteed rare or mythic rare, perfect for drafting or expanding your collection.",
    price: 499,
    priceDisplay: "$4.99",
    image: "/images/mini.svg",
    contents: [
      "15 Magic: The Gathering cards",
      "1 guaranteed rare or mythic rare",
      "1 full-art basic land possible",
    ],
    category: "Magic: The Gathering",
    inStock: true,
    createdAt: "2025-03-08",
  },
  {
    id: "yugioh-booster-pack",
    slug: "yugioh-booster-pack",
    name: "Yu-Gi-Oh! Booster Pack",
    tagline: "It's time to duel.",
    description:
      "One booster pack from the latest Yu-Gi-Oh! Trading Card Game set. Contains 9 cards with chances at Rare, Super Rare, Ultra Rare, and Secret Rare cards.",
    price: 449,
    priceDisplay: "$4.49",
    image: "/images/mini.svg",
    contents: [
      "9 Yu-Gi-Oh! TCG cards",
      "Chance at Ultra Rare and Secret Rare cards",
      "Varied rarity distribution",
    ],
    category: "Yu-Gi-Oh! Trading Card Game",
    inStock: true,
    createdAt: "2025-03-05",
  },
  {
    id: "one-piece-booster",
    slug: "one-piece-booster",
    name: "One Piece Card Game Booster",
    tagline: "Set sail for adventure.",
    description:
      "One booster pack from the One Piece Card Game. Contains 12 cards from the latest set featuring your favourite characters from the world of One Piece.",
    price: 449,
    priceDisplay: "$4.49",
    image: "/images/mini.svg",
    contents: [
      "12 One Piece Card Game cards",
      "Chance at Leader and rare character cards",
      "Full-art versions possible",
    ],
    category: "One Piece Card Game",
    inStock: true,
    createdAt: "2025-03-03",
  },
  {
    id: "lorcana-booster-pack",
    slug: "lorcana-booster-pack",
    name: "Disney Lorcana Booster Pack",
    tagline: "Magic, wonder, and rare glimmers.",
    description:
      "One booster pack from Disney Lorcana. Explore the magical world of Disney with 12 cards featuring beloved characters as Lorcana glimmers.",
    price: 549,
    priceDisplay: "$5.49",
    image: "/images/studio.svg",
    contents: [
      "12 Disney Lorcana cards",
      "1 guaranteed foil card",
      "Chance at Enchanted rarity",
    ],
    badge: "New",
    category: "Disney Lorcana",
    inStock: true,
    createdAt: "2025-03-01",
  },
  {
    id: "star-wars-unlimited-booster",
    slug: "star-wars-unlimited-booster",
    name: "Star Wars: Unlimited Booster",
    tagline: "The Force is in your hands.",
    description:
      "One booster pack from Star Wars: Unlimited. Features iconic Star Wars characters and moments across multiple eras of the galaxy far, far away.",
    price: 499,
    priceDisplay: "$4.99",
    image: "/images/mini.svg",
    contents: [
      "16 Star Wars: Unlimited cards",
      "1 guaranteed rare card",
      "Foil and showcase variants possible",
    ],
    category: "Star Wars: Unlimited",
    inStock: true,
    createdAt: "2025-02-28",
  },
  {
    id: "flesh-and-blood-booster",
    slug: "flesh-and-blood-booster",
    name: "Flesh and Blood Booster Pack",
    tagline: "For heroes who rise to the challenge.",
    description:
      "One booster pack from the latest Flesh and Blood expansion. Features the intense hero-versus-hero combat that makes Flesh and Blood the premier competitive card game.",
    price: 499,
    priceDisplay: "$4.99",
    image: "/images/midnight.svg",
    contents: [
      "16 Flesh and Blood cards",
      "1 guaranteed rare or higher",
      "Chance at Legendary or Fabled rarity",
    ],
    category: "Flesh and Blood",
    inStock: true,
    createdAt: "2025-02-25",
  },
  {
    id: "digimon-booster-pack",
    slug: "digimon-booster-pack",
    name: "Digimon Card Game Booster",
    tagline: "Digivolve your collection.",
    description:
      "One booster pack from the Digimon Card Game. Evolve your favourite Digimon partners and build powerful decks across multiple digital worlds.",
    price: 449,
    priceDisplay: "$4.49",
    image: "/images/mini.svg",
    contents: [
      "12 Digimon Card Game cards",
      "Chance at Rare, Super Rare, and Secret Rare cards",
      "Parallel art variants possible",
    ],
    category: "Digimon Card Game",
    inStock: true,
    createdAt: "2025-02-22",
  },
  {
    id: "dragon-ball-super-booster",
    slug: "dragon-ball-super-booster",
    name: "Dragon Ball Super Booster Pack",
    tagline: "Power up your collection.",
    description:
      "One booster pack from the Dragon Ball Super Card Game. Features iconic characters and moments from across the Dragon Ball universe.",
    price: 449,
    priceDisplay: "$4.49",
    image: "/images/midnight.svg",
    contents: [
      "12 Dragon Ball Super Card Game cards",
      "1 guaranteed Rare card",
      "Chance at Special Rare and Secret Rare",
    ],
    category: "Dragon Ball Super Card Game",
    inStock: true,
    createdAt: "2025-02-20",
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}
