export interface Product {
  id: string;
  slug: string;
  name: string;
  tagline: string;
  description: string;
  price: number; // in cents
  priceDisplay: string;
  image: string;
  stripePrice?: string;
  contents: string[];
  badge?: string;
  /** Category also doubles as the TCG game name for TCG products */
  category: string;
  inStock: boolean;
  createdAt: string; // ISO date string for "newest" sort
}

export const products: Product[] = [
  {
    id: "mini",
    slug: "mini",
    name: "Mini Crate",
    tagline: "A gentle introduction to the unknown.",
    description:
      "The Mini Crate holds one carefully curated mystery figure. Perfect for first-timers or those who savour small surprises. Each figure is sourced from premium collectible series — unwrapped slowly, one at a time.",
    price: 1499,
    priceDisplay: "$14.99",
    image: "/images/mini.svg",
    contents: ["1 mystery collectible figure", "Branded tissue wrap", "Collector card"],
    badge: "Starter",
    category: "Mystery Box",
    inStock: true,
    createdAt: "2025-01-20",
  },
  {
    id: "studio",
    slug: "studio",
    name: "Studio Crate",
    tagline: "The standard bearer of mystery.",
    description:
      "Three figures, three moments of discovery. The Studio Crate is our most popular tier — a balanced unboxing ritual that feels complete. Expect variety, quality, and at least one rare.",
    price: 3499,
    priceDisplay: "$34.99",
    image: "/images/studio.svg",
    contents: [
      "3 mystery collectible figures",
      "1 guaranteed rare figure",
      "Branded tissue wrap",
      "2x collector cards",
      "Sticker set",
    ],
    badge: "Popular",
    category: "Mystery Box",
    inStock: true,
    createdAt: "2025-01-20",
  },
  {
    id: "midnight",
    slug: "midnight",
    name: "Midnight Crate",
    tagline: "For those who embrace the premium unknown.",
    description:
      "Six figures. Two guaranteed rares. One ultra-rare possibility. The Midnight Crate is our most immersive experience — delivered in a matte black box with gold foil. Slow down. Breathe. Open.",
    price: 6999,
    priceDisplay: "$69.99",
    image: "/images/midnight.svg",
    contents: [
      "6 mystery collectible figures",
      "2 guaranteed rare figures",
      "1 chance at ultra-rare",
      "Matte black gift box with gold foil",
      "Premium tissue wrap",
      "4x collector cards",
      "Sticker set",
      "Exclusive Noir Crates bookmark",
    ],
    badge: "Premium",
    category: "Premium",
    inStock: true,
    createdAt: "2025-01-20",
  },
  {
    id: "labubu-forest",
    slug: "labubu-forest",
    name: "Forest Series Vol.1",
    tagline: "Tiny woodland creatures, infinite charm.",
    description:
      "Each blind box in the Forest Series contains one of twelve woodland-themed collectible figures. Soft palettes, intricate detail, and one hidden chase variant make every unboxing a delight.",
    price: 2299,
    priceDisplay: "$22.99",
    image: "/images/studio.svg",
    contents: [
      "1 mystery forest figure (1 of 12 designs)",
      "1 secret chase variant possible",
      "Collector card",
    ],
    badge: "New",
    category: "Series",
    inStock: true,
    createdAt: "2025-01-15",
  },
  {
    id: "neon-pop",
    slug: "neon-pop",
    name: "Neon Pop Vol.2",
    tagline: "Bold colour, bold surprises.",
    description:
      "The second volume of our Neon Pop series brings ten vibrant characters inspired by midnight city lights. Glow-in-the-dark variants are hidden throughout the run.",
    price: 1999,
    priceDisplay: "$19.99",
    image: "/images/mini.svg",
    contents: [
      "1 mystery neon figure (1 of 10 designs)",
      "Glow-in-the-dark variant possible",
      "Collector card",
    ],
    category: "Series",
    inStock: true,
    createdAt: "2025-01-10",
  },
  {
    id: "dark-matter",
    slug: "dark-matter",
    name: "Dark Matter Vol.1",
    tagline: "Limited. Cosmic. Unmissable.",
    description:
      "A limited-edition run of nine deep-space themed figures with metallic finishes. Once this batch sells out, it won't return. Includes one exclusive ultra-rare holographic variant.",
    price: 4499,
    priceDisplay: "$44.99",
    image: "/images/midnight.svg",
    contents: [
      "1 mystery cosmic figure (1 of 9 designs)",
      "Metallic finish on all variants",
      "1 holographic ultra-rare possible",
      "Premium collector card",
    ],
    badge: "Limited",
    category: "Limited Edition",
    inStock: true,
    createdAt: "2024-12-20",
  },
  {
    id: "crystal-dream",
    slug: "crystal-dream",
    name: "Crystal Dream",
    tagline: "Translucent wonder in every box.",
    description:
      "Eight delicate crystal-clear figures, each hand-cast in tinted resin. A meditative unboxing experience — slow, tactile, and deeply satisfying.",
    price: 2799,
    priceDisplay: "$27.99",
    image: "/images/mini.svg",
    contents: [
      "1 mystery crystal figure (1 of 8 designs)",
      "Hand-cast tinted resin",
      "Collector card",
      "Branded tissue wrap",
    ],
    category: "Mystery Box",
    inStock: true,
    createdAt: "2024-12-15",
  },
  {
    id: "sakura-bloom",
    slug: "sakura-bloom",
    name: "Sakura Bloom",
    tagline: "Spring in every box — while supplies last.",
    description:
      "Inspired by cherry-blossom season, the Sakura Bloom series features soft pinks, whites, and blush figures with petal-shaped bases. This run has sold out — join the waitlist for the next drop.",
    price: 2499,
    priceDisplay: "$24.99",
    image: "/images/studio.svg",
    contents: [
      "1 mystery sakura figure (1 of 8 designs)",
      "Petal-shaped base included",
      "Collector card",
    ],
    category: "Series",
    inStock: false,
    createdAt: "2024-12-01",
  },
  {
    id: "stellar-night",
    slug: "stellar-night",
    name: "Stellar Night",
    tagline: "Premium figures for the dedicated collector.",
    description:
      "Our premium Stellar Night collection features larger, more detailed figures with hand-painted accents. Six designs, each in a gift-grade matte box. A collector's showcase piece.",
    price: 3299,
    priceDisplay: "$32.99",
    image: "/images/midnight.svg",
    contents: [
      "1 premium stellar figure (1 of 6 designs)",
      "Hand-painted accents",
      "Matte gift box",
      "Certificate of design",
    ],
    badge: "Premium",
    category: "Premium",
    inStock: true,
    createdAt: "2024-11-20",
  },
  {
    id: "mossy-garden",
    slug: "mossy-garden",
    name: "Mossy Garden",
    tagline: "Quiet, earthy, and full of life.",
    description:
      "Ten peaceful garden-themed figures in muted greens and terracottas. Perfect as desk companions or shelf art. The Mossy Garden series pairs beautifully with our Mini Crate.",
    price: 1799,
    priceDisplay: "$17.99",
    image: "/images/mini.svg",
    contents: [
      "1 mystery garden figure (1 of 10 designs)",
      "Collector card",
      "Branded tissue wrap",
    ],
    category: "Mystery Box",
    inStock: true,
    createdAt: "2024-11-10",
  },

  // ─── Blind Boxes ───────────────────────────────────────────────────────────
  {
    id: "urban-nights-blind-box",
    slug: "urban-nights-blind-box",
    name: "Urban Nights Blind Box",
    tagline: "One figure. Infinite city vibes.",
    description:
      "Ten urban-inspired collectible figures capture the energy of city nights — neon signs, rooftop views, and street-level grit. Each single-figure blind box reveals one of ten designs, with one hidden limited chase variant.",
    price: 1299,
    priceDisplay: "$12.99",
    image: "/images/mini.svg",
    contents: [
      "1 mystery urban figure (1 of 10 designs)",
      "1 limited chase variant possible",
      "Collector card",
    ],
    badge: "New",
    category: "Blind Box",
    inStock: true,
    createdAt: "2025-02-15",
  },
  {
    id: "neon-dreamscape-blind-box",
    slug: "neon-dreamscape-blind-box",
    name: "Neon Dreamscape Blind Box",
    tagline: "Dream in colour, wake in surprise.",
    description:
      "Eight surreal dreamscape figures rendered in vivid neons and pastels. A single blind box holds one mystery figure — a pure unboxing moment, nothing more, nothing less.",
    price: 999,
    priceDisplay: "$9.99",
    image: "/images/mini.svg",
    contents: [
      "1 mystery dreamscape figure (1 of 8 designs)",
      "Collector card",
    ],
    category: "Blind Box",
    inStock: true,
    createdAt: "2025-02-10",
  },
  {
    id: "retro-arcade-blind-box",
    slug: "retro-arcade-blind-box",
    name: "Retro Arcade Blind Box",
    tagline: "Insert coin. Receive joy.",
    description:
      "Twelve pixel-art-inspired figures celebrate the golden age of arcades. Bold shapes, retro colours, and one secret rare variant hiding in the set.",
    price: 1199,
    priceDisplay: "$11.99",
    image: "/images/studio.svg",
    contents: [
      "1 mystery retro figure (1 of 12 designs)",
      "1 secret rare possible",
      "Collector card",
    ],
    category: "Blind Box",
    inStock: true,
    createdAt: "2025-02-05",
  },
  {
    id: "celestial-bloom-blind-box",
    slug: "celestial-bloom-blind-box",
    name: "Celestial Bloom Blind Box",
    tagline: "Stars blooming in every box.",
    description:
      "Eight celestial garden figures blend cosmic imagery with delicate florals. Soft metallics, fine detailing, and a meditative single-figure unboxing experience.",
    price: 1399,
    priceDisplay: "$13.99",
    image: "/images/studio.svg",
    contents: [
      "1 mystery celestial figure (1 of 8 designs)",
      "Collector card",
      "Branded tissue wrap",
    ],
    badge: "Popular",
    category: "Blind Box",
    inStock: true,
    createdAt: "2025-01-25",
  },

  // ─── Trading Card Games ────────────────────────────────────────────────────
  {
    id: "pokemon-tcg-booster-bundle",
    slug: "pokemon-tcg-booster-bundle",
    name: "Pokémon TCG Booster Bundle",
    tagline: "Catch rare cards with every pack.",
    description:
      "Three booster packs from the latest Pokémon Trading Card Game set. Each pack contains 10 cards with a chance at Rare, Ultra Rare, and Secret Rare holographic cards. Perfect for collectors and players alike.",
    price: 1499,
    priceDisplay: "$14.99",
    image: "/images/studio.svg",
    contents: [
      "3× Pokémon TCG booster packs (10 cards each)",
      "Chance at holo rares and full-arts",
      "Collector checklist card",
    ],
    badge: "Popular",
    category: "Pokémon Trading Card Game",
    inStock: true,
    createdAt: "2025-03-10",
  },
  {
    id: "pokemon-151-booster-box",
    slug: "pokemon-151-booster-box",
    name: "Pokémon 151 Booster Box",
    tagline: "Relive the original 151 with stunning new art.",
    description:
      "A full booster box from the Pokémon 151 set, celebrating the original generation of Pokémon. Contains 30 booster packs with beautifully illustrated cards featuring Gen 1 favourites. High pull rate for ultra rares.",
    price: 12999,
    priceDisplay: "$129.99",
    image: "/images/mini.svg",
    contents: [
      "30× Pokémon 151 booster packs (10 cards each)",
      "Chance at rare holos, ultra rares, and secret rares",
      "Full-art and special illustration cards possible",
    ],
    badge: "Popular",
    category: "Pokémon Trading Card Game",
    inStock: true,
    createdAt: "2025-03-11",
  },
  {
    id: "pokemon-mega-dream-ex-booster-box",
    slug: "pokemon-mega-dream-ex-booster-box",
    name: "Pokémon Mega Dream EX Booster Box",
    tagline: "Dream big with every pull.",
    description:
      "A booster box from the Pokémon Mega Dream EX set, packed with powerful EX Pokémon cards and stunning special art. Contains 30 booster packs ideal for competitive players and dedicated collectors.",
    price: 13999,
    priceDisplay: "$139.99",
    image: "/images/midnight.svg",
    contents: [
      "30× Pokémon Mega Dream EX booster packs (10 cards each)",
      "Chance at EX and full-art ultra rares",
      "Special illustration rare cards possible",
    ],
    category: "Pokémon Trading Card Game",
    inStock: true,
    createdAt: "2025-03-12",
  },
  {
    id: "pokemon-wild-force-booster-box",
    slug: "pokemon-wild-force-booster-box",
    name: "Pokémon Wild Force Booster Box",
    tagline: "Unleash the power of the wild.",
    description:
      "A booster box from the Pokémon Wild Force set, featuring fierce Pokémon and high-energy battle cards. Contains 30 booster packs loaded with wild power and rare finds for every trainer.",
    price: 11999,
    priceDisplay: "$119.99",
    image: "/images/studio.svg",
    contents: [
      "30× Pokémon Wild Force booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "EX and special art cards possible",
    ],
    category: "Pokémon Trading Card Game",
    inStock: true,
    createdAt: "2025-03-13",
  },
  {
    id: "pokemon-paradise-dragona-booster-box",
    slug: "pokemon-paradise-dragona-booster-box",
    name: "Pokémon Paradise Dragona Booster Box",
    tagline: "Discover a dragon paradise.",
    description:
      "A booster box from the Pokémon Paradise Dragona set, celebrating majestic Dragon-type Pokémon in lush, paradise-themed artwork. Contains 30 booster packs rich with rare Dragon cards.",
    price: 12999,
    priceDisplay: "$129.99",
    image: "/images/mini.svg",
    contents: [
      "30× Pokémon Paradise Dragona booster packs (10 cards each)",
      "Chance at Dragon-type rare holos and ultra rares",
      "Special illustration and full-art cards possible",
    ],
    badge: "New",
    category: "Pokémon Trading Card Game",
    inStock: true,
    createdAt: "2025-03-14",
  },
  {
    id: "pokemon-crimson-haze-booster-box",
    slug: "pokemon-crimson-haze-booster-box",
    name: "Pokémon Crimson Haze Booster Box",
    tagline: "Through the haze, rare cards await.",
    description:
      "A booster box from the Pokémon Crimson Haze set, draped in fiery crimson energy. Contains 30 booster packs featuring powerful Fire and Dragon Pokémon with striking new card art.",
    price: 11999,
    priceDisplay: "$119.99",
    image: "/images/midnight.svg",
    contents: [
      "30× Pokémon Crimson Haze booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "EX and special illustration cards possible",
    ],
    category: "Pokémon Trading Card Game",
    inStock: true,
    createdAt: "2025-03-15",
  },
  {
    id: "pokemon-heat-wave-arena-booster-box",
    slug: "pokemon-heat-wave-arena-booster-box",
    name: "Pokémon Heat Wave Arena Booster Box",
    tagline: "Feel the heat of battle.",
    description:
      "A booster box from the Pokémon Heat Wave Arena set, showcasing intense arena battles and scorching Pokémon power. Contains 30 booster packs perfect for competitive play and collection building.",
    price: 12999,
    priceDisplay: "$129.99",
    image: "/images/studio.svg",
    contents: [
      "30× Pokémon Heat Wave Arena booster packs (10 cards each)",
      "Chance at rare holos and ultra rares",
      "Arena-themed special illustration cards possible",
    ],
    category: "Pokémon Trading Card Game",
    inStock: true,
    createdAt: "2025-03-16",
  },
  {
    id: "pokemon-glory-of-team-rocket-booster-box",
    slug: "pokemon-glory-of-team-rocket-booster-box",
    name: "Pokémon Glory of Team Rocket Booster Box",
    tagline: "Prepare for trouble — and rare pulls.",
    description:
      "A booster box from the Pokémon Glory of Team Rocket set, celebrating the iconic villains of the Pokémon world. Contains 30 booster packs loaded with Team Rocket–themed cards and rare holographics.",
    price: 13999,
    priceDisplay: "$139.99",
    image: "/images/mini.svg",
    contents: [
      "30× Pokémon Glory of Team Rocket booster packs (10 cards each)",
      "Chance at Team Rocket rare holos and ultra rares",
      "Special illustration and full-art cards possible",
    ],
    badge: "New",
    category: "Pokémon Trading Card Game",
    inStock: true,
    createdAt: "2025-03-17",
  },
  {
    id: "pokemon-super-electric-breaker-booster-box",
    slug: "pokemon-super-electric-breaker-booster-box",
    name: "Pokémon Super Electric Breaker Booster Box",
    tagline: "Charge up your collection.",
    description:
      "A booster box from the Pokémon Super Electric Breaker set, crackling with Electric-type Pokémon power. Contains 30 booster packs featuring high-voltage cards and electrifying art across the entire set.",
    price: 12999,
    priceDisplay: "$129.99",
    image: "/images/midnight.svg",
    contents: [
      "30× Pokémon Super Electric Breaker booster packs (10 cards each)",
      "Chance at Electric-type rare holos and ultra rares",
      "Special illustration and EX cards possible",
    ],
    category: "Pokémon Trading Card Game",
    inStock: true,
    createdAt: "2025-03-18",
  },
  {
    id: "pokemon-terastal-festival-ex-booster-box",
    slug: "pokemon-terastal-festival-ex-booster-box",
    name: "Pokémon Terastal Festival EX Booster Box",
    tagline: "Celebrate the Terastal phenomenon.",
    description:
      "A booster box from the Pokémon Terastal Festival EX set, honouring the dazzling Terastal transformation mechanic. Contains 30 booster packs brimming with crystalline Terastal Pokémon and powerful EX cards.",
    price: 14999,
    priceDisplay: "$149.99",
    image: "/images/studio.svg",
    contents: [
      "30× Pokémon Terastal Festival EX booster packs (10 cards each)",
      "Chance at Terastal EX and full-art ultra rares",
      "Special illustration rare cards possible",
    ],
    badge: "Limited",
    category: "Pokémon Trading Card Game",
    inStock: true,
    createdAt: "2025-03-19",
  },
  {
    id: "magic-draft-booster",
    slug: "magic-draft-booster",
    name: "Magic: The Gathering Draft Booster",
    tagline: "Build your deck. Rule the battlefield.",
    description:
      "One draft booster pack from the latest Magic: The Gathering expansion. Contains 15 cards including one guaranteed rare or mythic rare, perfect for drafting or expanding your collection.",
    price: 499,
    priceDisplay: "$4.99",
    image: "/images/mini.svg",
    contents: [
      "15 Magic: The Gathering cards",
      "1 guaranteed rare or mythic rare",
      "1 full-art basic land possible",
    ],
    category: "Magic: The Gathering",
    inStock: true,
    createdAt: "2025-03-08",
  },
  {
    id: "yugioh-booster-pack",
    slug: "yugioh-booster-pack",
    name: "Yu-Gi-Oh! Booster Pack",
    tagline: "It's time to duel.",
    description:
      "One booster pack from the latest Yu-Gi-Oh! Trading Card Game set. Contains 9 cards with chances at Rare, Super Rare, Ultra Rare, and Secret Rare cards.",
    price: 449,
    priceDisplay: "$4.49",
    image: "/images/mini.svg",
    contents: [
      "9 Yu-Gi-Oh! TCG cards",
      "Chance at Ultra Rare and Secret Rare cards",
      "Varied rarity distribution",
    ],
    category: "Yu-Gi-Oh! Trading Card Game",
    inStock: true,
    createdAt: "2025-03-05",
  },
  {
    id: "one-piece-booster",
    slug: "one-piece-booster",
    name: "One Piece Card Game Booster",
    tagline: "Set sail for adventure.",
    description:
      "One booster pack from the One Piece Card Game. Contains 12 cards from the latest set featuring your favourite characters from the world of One Piece.",
    price: 449,
    priceDisplay: "$4.49",
    image: "/images/mini.svg",
    contents: [
      "12 One Piece Card Game cards",
      "Chance at Leader and rare character cards",
      "Full-art versions possible",
    ],
    category: "One Piece Card Game",
    inStock: true,
    createdAt: "2025-03-03",
  },
  {
    id: "lorcana-booster-pack",
    slug: "lorcana-booster-pack",
    name: "Disney Lorcana Booster Pack",
    tagline: "Magic, wonder, and rare glimmers.",
    description:
      "One booster pack from Disney Lorcana. Explore the magical world of Disney with 12 cards featuring beloved characters as Lorcana glimmers.",
    price: 549,
    priceDisplay: "$5.49",
    image: "/images/studio.svg",
    contents: [
      "12 Disney Lorcana cards",
      "1 guaranteed foil card",
      "Chance at Enchanted rarity",
    ],
    badge: "New",
    category: "Disney Lorcana",
    inStock: true,
    createdAt: "2025-03-01",
  },
  {
    id: "star-wars-unlimited-booster",
    slug: "star-wars-unlimited-booster",
    name: "Star Wars: Unlimited Booster",
    tagline: "The Force is in your hands.",
    description:
      "One booster pack from Star Wars: Unlimited. Features iconic Star Wars characters and moments across multiple eras of the galaxy far, far away.",
    price: 499,
    priceDisplay: "$4.99",
    image: "/images/mini.svg",
    contents: [
      "16 Star Wars: Unlimited cards",
      "1 guaranteed rare card",
      "Foil and showcase variants possible",
    ],
    category: "Star Wars: Unlimited",
    inStock: true,
    createdAt: "2025-02-28",
  },
  {
    id: "flesh-and-blood-booster",
    slug: "flesh-and-blood-booster",
    name: "Flesh and Blood Booster Pack",
    tagline: "For heroes who rise to the challenge.",
    description:
      "One booster pack from the latest Flesh and Blood expansion. Features the intense hero-versus-hero combat that makes Flesh and Blood the premier competitive card game.",
    price: 499,
    priceDisplay: "$4.99",
    image: "/images/midnight.svg",
    contents: [
      "16 Flesh and Blood cards",
      "1 guaranteed rare or higher",
      "Chance at Legendary or Fabled rarity",
    ],
    category: "Flesh and Blood",
    inStock: true,
    createdAt: "2025-02-25",
  },
  {
    id: "digimon-booster-pack",
    slug: "digimon-booster-pack",
    name: "Digimon Card Game Booster",
    tagline: "Digivolve your collection.",
    description:
      "One booster pack from the Digimon Card Game. Evolve your favourite Digimon partners and build powerful decks across multiple digital worlds.",
    price: 449,
    priceDisplay: "$4.49",
    image: "/images/mini.svg",
    contents: [
      "12 Digimon Card Game cards",
      "Chance at Rare, Super Rare, and Secret Rare cards",
      "Parallel art variants possible",
    ],
    category: "Digimon Card Game",
    inStock: true,
    createdAt: "2025-02-22",
  },
  {
    id: "dragon-ball-super-booster",
    slug: "dragon-ball-super-booster",
    name: "Dragon Ball Super Booster Pack",
    tagline: "Power up your collection.",
    description:
      "One booster pack from the Dragon Ball Super Card Game. Features iconic characters and moments from across the Dragon Ball universe.",
    price: 449,
    priceDisplay: "$4.49",
    image: "/images/midnight.svg",
    contents: [
      "12 Dragon Ball Super Card Game cards",
      "1 guaranteed Rare card",
      "Chance at Special Rare and Secret Rare",
    ],
    category: "Dragon Ball Super Card Game",
    inStock: true,
    createdAt: "2025-02-20",
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}
